---
title: "2024.08.09_factice_Stem_height"
author: "Laurie Magnin"
date: "2024-08-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggpubr)
library(rstatix)
library(dplyr)
library(MASS)
library(car)
library(emmeans)
library(glmmTMB)


Notations_structures_factice <- read.csv("~/working/2023_Analyses_Plante_Factice/1_Data/Notations_structures_factice.csv", sep=";")

Notations_structures_factice$Elongation<-as.numeric(Notations_structures_factice$Elongation)
Notations_structures_factice$modality<- as.factor(Notations_structures_factice$modality)
Notations_structures_factice$plot<- as.factor(Notations_structures_factice$plot)

data_PB<-subset(Notations_structures_factice, Notations_structures_factice$date.1 == "2024-03-26"|Notations_structures_factice$date.1 == "2023-03-21")
head(data_PB)

data_PB$h_tige <- as.numeric(data_PB$h_tige)

```

## Exploratory table

```{r exploratory, echo=FALSE}


Elongation_AV <-data_PB %>%                                 # Group data
  group_by( modality, parcelle) %>%
  dplyr::summarize(gr_sum = mean(h_tige), sd = sd(h_tige), n = n(),
                   se = sd / sqrt(n)) %>% 
  as.data.frame()

plot1<-ggplot(Elongation_AV, aes(x=modality, y=gr_sum, fill=modality)) + 
  geom_bar(stat="identity", color="black", position=position_dodge()) +
  geom_errorbar(aes(ymin=gr_sum-se, ymax=gr_sum+se), width=.2,
                position=position_dodge(.9)) 

plot1+labs(title="Average stem height at pollen beetle immigration", x="Culture type", y = "Stem elongation (cm)") + 
  scale_y_continuous(breaks=seq(0, 100, 10))+
  theme_minimal() +
  scale_fill_manual(values=c('#E69F00','#999999','#69b3a2','seagreen'))+
  facet_wrap(vars(parcelle))

```

## Model 

```{r model, echo=FALSE, message=FALSE}

#Standardization of the data 

standardize = function(x){ 
  z <- (x - mean(x)) / sd(x) 
  return( z) 
} 

Notations_structures_factice <- read.csv("~/working/2023_Analyses_Plante_Factice/1_Data/Notations_structures_factice.csv", sep=";")
Notations_structures_factice <- subset(Notations_structures_factice, Notations_structures_factice$parcelle == "2022- P1")
Notations_structures_factice_P1 <- subset(Notations_structures_factice, Notations_structures_factice$date.1 == "2023-03-21")
Notations_structures_factice_P1$h_tige <- as.numeric(Notations_structures_factice_P1$h_tige)
Notations_structures_factice_P1 <- subset(Notations_structures_factice_P1, Notations_structures_factice_P1$h_tige != 54)
Notations_structures_factice_P1[c('h_tige')]<- apply(Notations_structures_factice_P1[c('h_tige')], 2, standardize) 


Notations_structures_factice <- read.csv("~/working/2023_Analyses_Plante_Factice/1_Data/Notations_structures_factice.csv", sep=";")
Notations_structures_factice <- subset(Notations_structures_factice, Notations_structures_factice$parcelle == "2022- P2")
Notations_structures_factice_P2 <- subset(Notations_structures_factice, Notations_structures_factice$date.1 == "2023-03-21")
Notations_structures_factice_P2$h_tige <- as.numeric(Notations_structures_factice_P2$h_tige)
Notations_structures_factice_P2[c('h_tige')]<- apply(Notations_structures_factice_P2[c('h_tige')], 2, standardize) 

Notations_structures_factice <- read.csv("~/working/2023_Analyses_Plante_Factice/1_Data/Notations_structures_factice.csv", sep=";")
Notations_structures_factice <- subset(Notations_structures_factice, Notations_structures_factice$parcelle == "2023- P3")
Notations_structures_factice_P3 <- subset(Notations_structures_factice, Notations_structures_factice$date.1 == "2024-03-26")
Notations_structures_factice_P3$h_tige <- as.numeric(Notations_structures_factice_P3$h_tige)
Notations_structures_factice_P3 <- subset(Notations_structures_factice_P3, Notations_structures_factice_P3$h_tige != 36)
Notations_structures_factice_P3[c('h_tige')]<- apply(Notations_structures_factice_P3[c('h_tige')], 2, standardize) 

data_PB <- rbind(Notations_structures_factice_P1, Notations_structures_factice_P2, Notations_structures_factice_P3)
data_PB$plot <- as.factor(data_PB$plot)
data_PB$h_tige <- as.numeric (data_PB$h_tige)

model <- lm(h_tige ~ parcelle/plot + modality , data=data_PB)

model.metrics <- augment(model) 
head(model.metrics)

qqnorm(model.metrics$.resid)
qqline(model.metrics$.resid)

#Homogénéité des variances 
model.metrics %>% levene_test(.resid ~ modality) #OK

# Valeurs aberrantes 
model.metrics %>% filter(abs(.std.resid) > 3) %>% as.data.frame() #OK

```

## Model output

```{r model output, echo=FALSE, message=FALSE, warning=FALSE}
data_PB %>% anova_test(h_tige ~ parcelle/plot + modality)

library(emmeans)
pwc <- 
  emmeans(model,pairwise~modality )
pwc

```

## Result figure and effect 

```{r results, echo=FALSE, , message=FALSE}
emm<-emmeans(model, ~ modality, type = 'response')

plot(emm, by = NULL, comparisons = FALSE, adjust = "tukey", horizontal = FALSE)

library('data.table')

emm<- as.data.table(emm)

hundred <- emm[[1,2]]
emm$effect_percent <- (emm$emmean/hundred*100)-100 

emm


plot1<-ggplot(emm, aes(x=modality, y=emmean, colour = modality )) + 
  geom_point()+
  geom_errorbar(aes(ymin=emmean-SE, ymax=emmean+SE), width=.2,
                position=position_dodge(.9))+
  scale_colour_manual(values=c('#E69F00','#999999','#69b3a2','seagreen'))+
  scale_y_continuous(limits = c(-0.5,0.5))

plot1+labs(title="Relative stem height at pollen beetle immigration", x="Modality", y = "EMMean of standardized stem height")+
  theme_classic() 
```
