---
title: "Phyllotetra spp. bites on cotyledon"
author: "Laurie Magnin"
date: "2024-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

Morsures_Altises_factice <- read.csv("~/working/2023_Analyses_Plante_Factice/1_Data/Morsures_Altises_factice_2.csv", sep=";")

Morsures_Altises_factice <-subset(Morsures_Altises_factice, date %in% c('22.09.2022', '11.09.2023'))
head(Morsures_Altises_factice)

```

## Exploratory figure


```{r exploratory, echo=FALSE}
library(ggplot2)

ggplot(Morsures_Altises_factice, aes(x=modalite, y=degat, color=modalite))  +
  geom_violin() + labs(title="Number of bites on cotyledons",x="Modality", y = "Number of bites on cotyledons")+
  stat_summary(fun=mean, geom="point", shape=4, size=2) +
  stat_summary(fun=median, geom="point", shape=16, size=2) +
  theme_classic() +
  scale_color_manual(values=c('#E69F00','#999999','#69b3a2','seagreen'))+
  facet_wrap(vars(parcelle))

```

## Model 

```{r model, echo=FALSE, message=FALSE}
library(glmmTMB)

mymodel<- glmmTMB(degat ~  modalite +(1|plot/parcelle), data= Morsures_Altises_factice, nbinom1)

summary(mymodel)

library(DHARMa)

n_sim <- 500

simulationOutput <- simulateResiduals(fittedModel = mymodel, n = n_sim)
plot(simulationOutput, asFactor = F)

testDispersion(simulationOutput)

plot(simulationOutput, form = Morsures_Altises_factice$modalite)

```

## Model output

```{r model output, echo=FALSE, message=FALSE, warning=FALSE}
library(car)
Anova(mymodel, type=3)

library(emmeans)

emmeans(mymodel, list(pairwise ~ modalite), adjust = "tukey")

```

## Result figure and effect 

```{r results, echo=FALSE, , message=FALSE}
emm<-emmeans(mymodel, ~ modalite, type = 'response')

plot(emm, by = NULL, comparisons = FALSE, adjust = "tukey", horizontal = FALSE)

library('data.table')

emm<- as.data.table(emm)

hundred <- emm[[1,2]]
emm$effect_percent <- (emm$response/hundred*100)-100 

emm

plot_bites <- ggplot(emm, aes(x=modalite, y=response, fill = modalite )) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  scale_fill_manual(values=c('#E69F00','#999999','#69b3a2','seagreen'))+
  geom_errorbar(aes(ymin=response-SE, ymax=response+SE), width=.2,
                position=position_dodge(.9)) +
  scale_y_continuous(limits = c(0, 14), breaks = c(0, 2, 4, 6, 8, 10, 12))

plot_bites +labs(title="Number of bites on cotyledons", x="Modality", y = "EMMean number of bites on cotyledons")+
  theme_classic() 

```
