---
title: "2024.08.09_Factice_CollarDiameter"
author: "Laurie Magnin"
date: "2024-08-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggpubr)
library(rstatix)
library(dplyr)
library(MASS)
library(countreg)
library(car)
library(emmeans)
library(glmmTMB)

Notations_structures_factice <-read.csv("~/working/2023_Analyses_Plante_Factice/1_Data/Notations_structures_factice.csv", sep=";")

Notations_structures_factice <- subset(Notations_structures_factice, date.1== "2022-11-08" | date.1== "2023-11-21")
head(Notations_structures_factice)
Notations_structures_factice$d_collet<-as.numeric(Notations_structures_factice$d_collet)
Notations_structures_factice$modality<- as.factor(Notations_structures_factice$modality)
Notations_structures_factice$plot<- as.factor(Notations_structures_factice$plot)

```

## Exploratory table


```{r exploratory, echo=FALSE}

collar_average <-Notations_structures_factice %>%                                 # Group data
  group_by( modality, parcelle) %>%
  dplyr::summarize(gr_sum = mean(d_collet), sd = sd(d_collet), n = n(),
                   se = sd / sqrt(n)) %>% 
  as.data.frame()

plot1<-ggplot(collar_average, aes(x=modality, y=gr_sum, fill=modality)) + 
  geom_bar(stat="identity", color="black", position=position_dodge()) +
  geom_errorbar(aes(ymin=gr_sum-se, ymax=gr_sum+se), width=.2,
                position=position_dodge(.9)) 

plot1+labs(title="Average collar diameter before winter (21.11.2023) N=120", x="Culture type", y = "Collar diameter (mm)") + 
  scale_y_continuous(breaks=seq(0, 20, 2))+
  theme_minimal() +
  scale_fill_manual(values=c('#E69F00','#999999','#69b3a2','seagreen'))+
  facet_wrap(vars(parcelle))

```

## Model 

```{r model, echo=FALSE, message=FALSE}
model <- lm(sqrt(d_collet) ~parcelle/plot+ modality  , data=Notations_structures_factice) #calculer le model, la covariable passe en premier 

model.metrics <- augment(model) 
head(model.metrics)

qqnorm(model.metrics$.resid)
qqline(model.metrics$.resid)

#Homogénéité des variances 

model.metrics %>% levene_test(.resid ~ modality) #OK

# Valeurs aberrantes 

model.metrics %>% filter(abs(.std.resid) > 3) %>% as.data.frame() #OK

```

## Model output

```{r model output, echo=FALSE, message=FALSE, warning=FALSE}
Notations_structures_factice$sqrt_d_collet <- sqrt(Notations_structures_factice$d_collet)

Notations_structures_factice  %>% anova_test(sqrt_d_collet ~ parcelle/plot + modality  )

library(emmeans)

pwc <- 
  emmeans(model,pairwise~modality)
pwc
```

## Result figure and effect 

```{r results, echo=FALSE, , message=FALSE}
emm<-emmeans(model, ~ modality, type = 'response')

plot(emm, by = NULL, comparisons = FALSE, adjust = "tukey", horizontal = FALSE)

library('data.table')

emm<- as.data.table(emm)

hundred <- emm[[1,2]]
emm$effect_percent <- (emm$response/hundred*100)-100 

emm

plot_bites <- ggplot(emm, aes(x=modality, y=response, fill = modality )) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  scale_fill_manual(values=c('#E69F00','#999999','#69b3a2','seagreen'))+
  geom_errorbar(aes(ymin=response-SE, ymax=response+SE), width=.2,
                position=position_dodge(.9)) +
  scale_y_continuous(limits = c(0, 17), breaks = c(0, 5, 10, 15))

plot_bites +labs(title="Collar diameter at flea beetle migration", x="Modality", y = "EMMean collar diameter (cm)")+
  theme_classic() 

```
