---
title: "2024.08.02_Factice_P.chrysocephala_larvae"
author: "Laurie Magnin"
date: "2024-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Berlese <- read.csv("~/working/2023_Analyses_Plante_Factice/1_Data/Berlese_Laurie_factice_2023.csv", sep=";")
head (Berlese)
head (Berlese)

Berlese$larva.plant <- Berlese$nb_larva_FB /Berlese$count

Berlese$larva.plant <- as.integer(Berlese$larva.plant)
```

## Exploratory figure


```{r exploratory, echo=FALSE, message=FALSE}
library(ggplot2)
library("dplyr")

Berlese_sum <- Berlese %>%                                 # Group data
  group_by(modality, parcelle) %>%
  dplyr::summarize(gr_sum = mean(larva.plant), sd = sd(larva.plant), n = n(),
                   se = sd / sqrt(n)) %>% 
  as.data.frame()

Berlese_sum$gr_sum <- as.numeric(Berlese_sum$gr_sum)

plot1<-ggplot(Berlese_sum, aes(x=modality, y=gr_sum, fill = modality )) + 
  geom_point()+
  geom_errorbar(aes(ymin=gr_sum-se, ymax=gr_sum+se), width=.2,
                position=position_dodge(.9))+
  scale_fill_manual(values=c('#E69F00','#999999','#69b3a2','seagreen'))+
  scale_y_continuous(limits = c(0, 12.5))+
  facet_wrap(vars(parcelle))

plot1+labs(title="Number of adult flea beetle trapped per sticky trap per week", x="Modality", y = "Number of adult flea beetle")+
  theme_classic() 

```

## Model 

```{r model, echo=FALSE, message=FALSE}

Berlese$bloc <- as.factor(Berlese$bloc)

library ('glmmTMB')

mymodel<- glmmTMB(larva.plant ~  modality + (1|parcelle/bloc), data= Berlese, family = nbinom2)

summary(mymodel)

library(DHARMa)

n_sim <- 500

simulationOutput <- simulateResiduals(fittedModel = mymodel, n = n_sim)
plot(simulationOutput, asFactor = F)

testDispersion(simulationOutput)

plot(simulationOutput, form = Berlese$modality)
```

## Model output

```{r model output, echo=FALSE, message=FALSE, warning=FALSE}
library(car)
library(emmeans)
Anova(mymodel, type=3)

Berlese$modality <- as.factor(Berlese$modality)

emmeans(mymodel, list(pairwise ~ modality), adjust = "tukey")

```

## Result figure and effect 

```{r results, echo=FALSE, , message=FALSE}

emm<-emmeans(mymodel, ~ modality, type = 'response')

library('data.table')

emm<- as.data.table(emm)

hundred <- emm[[1,2]]
emm$effect_percent <- (emm$response/hundred*100)-100 

emm

plot_bites <- ggplot(emm, aes(x=modality, y=response, fill = modality )) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  scale_fill_manual(values=c('#E69F00','#999999','#69b3a2','seagreen'))+
  geom_errorbar(aes(ymin=response-SE, ymax=response+SE), width=.2,
                position=position_dodge(.9)) +
  scale_y_continuous(limits = c(0, 3), breaks = c(0, 1, 2, 3))

plot_bites +labs(title="Number of larvae per plant", x="Modality", y = "EMMean number of larvae per plant")+
  theme_classic() 

```
